sudo: true
go_import_path: github.com/intuit/katlas

dist: xenial
language: go

go:
  - 1.11.x

services:
  - docker

install:
 - cd $TRAVIS_BUILD_DIR/service && make all
 #- cd $TRAVIS_BUILD_DIR/app && yarn install

before_script:
 - ifconfig -a
 - docker pull dgraph/dgraph
 - mkdir -p /tmp/data
 - docker run -d -it -p 5080:5080 -p 6080:6080 -p 8080:8080 -p 9080:9080 -p 8000:8000 -v /tmp/data:/dgraph --name diggy dgraph/dgraph dgraph zero
 - docker exec -d -it diggy dgraph alpha --lru_mb 2048 --zero localhost:5080
 - sleep 5s
 - netstat -anl
 - docker ps -a
 - curl -sw '%{http_code}\n' http://localhost:8080/health
 - TRAVIS_COMMIT_SHORTID="${TRAVIS_COMMIT:0:7}"
 - echo "${TRAVIS_COMMIT_SHORTID}"
script:
 - cd $TRAVIS_BUILD_DIR/service
 - pwd
 - ls -l
 - ls -l util/
 - ls -l [ab]*/
 - docker build --no-cache -f Dockerfile -t katlas-service:${TRAVIS_COMMIT_SHORTID} .
 - docker images katlas-service:${TRAVIS_COMMIT_SHORTID}
after_success:
 - cd $TRAVIS_BUILD_DIR/service
# - go run server.go 2> output.out &
 - HOST=172.17.0.1
 - docker run -d -it -p 8011:8011 -e ENV_NAMESPACE=qal -e SERVER_TYPE=http -e DGRAPH_HOST=$HOST:9080 --name katlas-service katlas-service:${TRAVIS_COMMIT_SHORTID}
 #
 - docker logs katlas-service
 - sleep 10s
 - docker ps -a
 - lsof -i :8080
 - netstat -anl
 - curl -sw '%{http_code}\n' http://localhost:8080/health
 - curl -sw '%{http_code}\n' http://localhost:8011/health
 - docker network create katlasnet
 - docker network connect katlasnet diggy
 - docker network connect katlasnet katlas-service
 #- cat output.out
 #- curl http://localhost:8080/query -XPOST -d $'{me(func: has(starring)) {name}}'
 - curl -sw '%{http_code}\n' http://localhost:8080/health
 - curl -sw '%{http_code}\n' http://localhost:8011/health
 - curl -sw '%{http_code}\n' http://localhost:8011/v1/query?name=pod
 - statusCode=$(curl -sw '%{http_code}\n' http://localhost:8011/v1/query?name=pod -o /dev/null)
 - echo $statusCode
 - |
   if [ $statusCode -ne "200" ]; then
       echo "Integration Test - Fail!";
   else
         echo "Integration Test - Success!";
   fi
